name: lab_env_2
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2
  - argcomplete=1.12.3
  - asttokens=3.0.0
  - attrs=25.3.0
  - backports=1.0
  - backports.functools_lru_cache=2.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cachetools=5.5.2
  - chardet=5.2.0
  - colorama=0.4.6
  - colorlog=5.0.1
  - comm=0.2.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - dependency-groups=1.3.0
  - distlib=0.3.8
  - exceptiongroup=1.2.2
  - executing=0.8.3
  - filelock=3.18.0
  - importlib_metadata=4.13.0
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - libcxx=14.0.6
  - libexpat=2.7.0
  - libffi=3.4.6
  - liblzma=5.8.1
  - libsodium=1.0.18
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.6
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nox=2025.2.9
  - openssl=3.5.0
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=25.0.1
  - platformdirs=4.3.7
  - pluggy=1.5.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.19.1
  - pyproject-api=1.9.0
  - python=3.11.12
  - python-dateutil=2.9.0post0
  - python_abi=3.11
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=78.1.0
  - six=1.17.0
  - stack_data=0.2.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.4.2
  - tox=4.25.0
  - traitlets=5.14.3
  - virtualenv=20.30.0
  - wcwidth=0.2.5
  - wheel=0.45.1
  - zeromq=4.3.5
  - zipp=3.21.0
  - pip:
      - aiosqlite==0.21.0
      - alembic==1.15.2
      - annotated-types==0.7.0
      - anyio==4.6.0
      - appdirs==1.4.4
      - apprise==1.9.3
      - asgi-lifespan==2.1.0
      - async-timeout==5.0.1
      - asyncpg==0.29.0
      - blinker==1.9.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - cfgv==3.4.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - contourpy==1.3.2
      - coolname==2.2.0
      - croniter==5.0.1
      - cryptography==44.0.2
      - cycler==0.12.1
      - databricks-sdk==0.50.0
      - dateparser==1.2.1
      - deprecated==1.2.18
      - deprecation==2.1.0
      - distro==1.9.0
      - dnspython==2.7.0
      - docker==7.1.0
      - durationpy==0.9
      - dynaconf==3.2.10
      - email-validator==2.2.0
      - evidently==0.4.40
      - faker==37.1.0
      - fastapi==0.115.12
      - flask==3.1.0
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.39.0
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.2.0
      - griffe==1.7.2
      - gunicorn==23.0.0
      - h11==0.14.0
      - h2==4.2.0
      - hpack==4.1.0
      - httpcore==1.0.8
      - httptools==0.6.4
      - httpx==0.28.1
      - humanize==4.12.2
      - hyperframe==6.1.0
      - identify==2.6.10
      - idna==3.10
      - importlib-metadata==8.6.1
      - importlib-resources==6.4.5
      - iniconfig==2.1.0
      - iterative-telemetry==0.0.10
      - itsdangerous==2.2.0
      - jinja2-humanize-extension==0.4.0
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - kubernetes==31.0.0
      - litestar==2.15.2
      - litestar-htmx==0.4.1
      - mako==1.3.10
      - markdown==3.8
      - markdown-it-py==3.0.0
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mlflow==2.21.3
      - mlflow-skinny==2.21.3
      - msgspec==0.19.0
      - multidict==6.4.3
      - multipart==1.2.1
      - mypy-extensions==1.0.0
      - nltk==3.9.1
      - nodeenv==1.9.1
      - numpy==2.0.2
      - oauthlib==3.2.2
      - opentelemetry-api==1.32.1
      - opentelemetry-sdk==1.32.1
      - opentelemetry-semantic-conventions==0.53b1
      - orjson==3.10.16
      - pandas==2.2.3
      - pathspec==0.12.1
      - patsy==1.0.1
      - pendulum==2.1.2
      - pillow==11.2.1
      - plotly==5.24.1
      - polyfactory==2.21.0
      - pre-commit==4.2.0
      - prefect==2.20.17
      - protobuf==5.29.4
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pyparsing==3.2.3
      - pytest==8.3.5
      - python-dotenv==1.1.0
      - python-multipart==0.0.20
      - python-slugify==8.0.4
      - pytz==2024.2
      - pytzdata==2020.1
      - pyyaml==6.0.2
      - readchar==4.2.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rich==13.9.4
      - rich-click==1.8.8
      - rpds-py==0.24.0
      - rsa==4.9.1
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.35
      - sqlparse==0.5.3
      - starlette==0.46.2
      - statsmodels==0.14.4
      - tenacity==9.1.2
      - text-unidecode==1.3
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - tqdm==4.67.1
      - typer==0.15.2
      - typing-extensions==4.13.2
      - typing-inspect==0.9.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - tzlocal==5.3.1
      - ujson==5.10.0
      - urllib3==2.4.0
      - uuid6==2024.7.10
      - uvicorn==0.34.1
      - uvloop==0.21.0
      - watchdog==6.0.0
      - watchfiles==1.0.5
      - websocket-client==1.8.0
      - websockets==13.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
