grafana:
  enabled: false

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      # This is used to scrape from the otel-collector exposed metrics
      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel-collector-opentelemetry-collector.otel-collector.svc.cluster.local:9090']
      # This is used to scrape from the federated Prometheus on the prod
      # and test k8s clusters
      - job_name: 'federate'
        honor_labels: true
        metrics_path: '/federate'
        params:
          'match[]':
            - '{__name__=~"node_.*"}'
            - '{__name__=~"kube_.*"}'
            - '{__name__=~"container_.*"}'
            - '{job="kubernetes-apiservers"}'
            - 'up'
        static_configs:
          - targets:
            - '172.18.0.120:9090'
            - '172.18.0.140:9090'
