datasources:
  datasources.yaml:
    datasources:
      - name: loki
        type: loki
        access: proxy
        url: "{{ .Values.lokiUrl }}"
        uid: eeauksdnf5am8b
        jsonData:
          derivedFields:
            - name: Trace
              datasourceUid: deauja5skyayof
              matcherRegex: trace_id
              matcherType: label
              url: ${__value.raw}
              urlDisplayLabel: Trace

      - name: prometheus
        type: prometheus
        access: proxy
        url: "{{ .Values.prometheusUrl }}"
        uid: eeauidosfncw0a
        isDefault: true
        jsonData:
          httpMethod: POST
          exemplarTraceIdDestinations:
            - name: trace_id
              datasourceUid: deauja5skyayof

      - name: tempo
        type: tempo
        access: proxy
        url: "{{ .Values.tempoUrl }}"
        uid: deauja5skyayof
        jsonData:
          tracesToLogsV2:
            customQuery: false
            datasourceUid: eeauksdnf5am8b
            filterByTraceID: true
            tags:
              - key: trace_id
                value: Trace ID
          tracesToMetrics:
            datasourceUid: eeauidosfncw0a
            queries: []
            tags:
              - key: trace_id
                value: Trace ID
