datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: loki
        uid: dsloki
        type: loki
        access: proxy
        url: http://loki-gateway.loki.svc.cluster.local:80
        jsonData:
          derivedFields:
            - datasourceUid: dstempo
              matcherRegex: "trace_id"
              matcherType: label
              name: "Trace"
              url: "$${__value.raw}"
              urlDisplayLabel: "Trace"
      - name: prometheus
        uid: dsprometheus
        type: prometheus
        access: proxy
        url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        isDefault: true
        jsonData:
          exemplarTraceIdDestinations:
            - datasourceUid: dstempo
              name: trace_id
          httpMethod: POST
      - name: tempo
        uid: dstempo
        type: tempo
        access: proxy
        url: http://tempo-query-frontend.tempo.svc.cluster.local:3100
        jsonData:
          tracesToLogsV2:
            customQuery: false
            datasourceUid: dsloki
            filterByTraceID: true
            tags:
              - key: trace_id
                value: Trace ID
          tracesToMetrics:
            datasourceUid: dsprometheus
            queries: []
            tags:
              - key: trace_id
                value: Trace ID
