apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-secret
  labels:
    app: webserver-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-secret
  template:
    metadata:
      labels:
        app: webserver-secret
    spec:
      serviceAccountName: internal-app
      containers:
      - name: webserver-secret
        image: php:apache
        envFrom:
        - secretRef:
            name: secretkv
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: secretkv
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: secretkv
              key: password
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: docroot
          mountPath: /var/www/html
      volumes:
      - name: docroot
        configMap:
          name: index-php
      - name: secretkv
        secret:
          secretName: secretkv
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-secret
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webserver-secret
