apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: test-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.18.0.120-172.18.0.130
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: test-l2adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - test-ip-pool
